### ISSUE TITLE
Stop Server Material Icon

### ISSUE THREAD

**Issue by Golumpa** [SpaceCP/Bugs#142]
Not sure if this is intentional or not but it has been bugging me why the material icon for stopping the server is a pause button and not the stop button that comes with the material icon pack?

**Comment by tintinhamans** [comment]
I wondered about this too.

**Comment by Antariano** [comment]
There's two main reasons here, but I'm open for a discussion :)

First, a pause icon is more immediately recognizable then a stop icon because it's not as equivocal. A square is more prone to misinterpretation than two stripes.

Second, from a technical standpoint, you're shutting your server down, but we didn't want to convey the feeling of "completely" shutting it down. As in: starting it back up is effortless and immediate. A "stop" icon has a more ominous implication. Am I stopping it completely? What will happen? A "pause" icon translates better to the swiftness of the action.

**Comment by Golumpa** [comment]
I understand all of what you said and i can see why a pause button is in use right now. The other icons make perfect sense the play button starts the server the suspend button terminates it immediately. To me minecraft has no "pause" and the command "stop" stops the server.

Now i know the reason i understand it and its not a problem but i just want to state my thinking behind it.

**Comment by narrowtux** [comment]
Have you thought about just using the word "Stop" instead of an icon?
