### ISSUE TITLE
Front End Text Field

### ISSUE THREAD

**Issue by TheBloodHound** [SpaceCP/Bugs#27]
At times, textfields' words such as Username, Email, Password, Host, Name, etc. sometimes don't go up above the text inputted so sometimes it would show (for example) Email overlapping email@example.com.

**Comment by MiniDigger** [comment]
Could you provide screenshots and your browser and os version?

**Comment by TheBloodHound** [comment]
I don't have screenshots at the moment but I am using Safari Version 9.0 on Mac OS X El Capitan Version 10.11

**Comment by JamyDev** [comment]
When this happens, are they yellow too?

**Comment by TheBloodHound** [comment]
No. Although I do remember I was switching between the website and another window.

**Comment by Antariano** [comment]
Please provide screenshot and steps to reproduce so we can fix the issue.

**Comment by TheBloodHound** [comment]
Okay, if it happens again I will be sure to take screenshots.

**Comment by Antariano** [comment]
Closing for now. Will open if it happens again.

**Comment by TheBloodHound** [comment]
http://prntscr.com/9fxhvf It happened.

**Comment by TheBloodHound** [comment]
I found out how to make it happen: I click on the input box, switch to another tab, and come back. http://prntscr.com/9fxi97 I did it with all of these using the method provided.

**Comment by MiniDigger** [comment]
Can't reproduce on Chrome 47, Firefox 42 (Win10) and Chrome on Android (47 on CM12.1 5.1.1)
Could be a safari problem.
While testing I noticed something related: when Chrome tries to insert my password into the field the same glitch occurs. It is fixed by pressing somewhere on the site (i pressed to logo) https://gyazo.com/fa00d2340a1b6d69f30b40f4b6314144
