### ISSUE TITLE
server config server.properties editor missing useful values

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#49]
many useful and functional settings are missing from the server.properties editor. obvious things like the level-seed, pvp and enable-command-block cannot be edited.

i'm very mindful of the fact that not every single option needs to be exposed here, but perhaps we need a "basic" and an "advanced" section/tab. advanced permits the user to edit the server.properties natively, but "basic" contains a subset of items.

i think the server.properties editor needs to be a bit smarter as well. rather than a spaced out long scroll list of options, it should be a nicer form with pulldowns for "survival" and "creative" rather than 0 and 1. units should be listed alongside fields such as "max-tick-time".

the purpose of a control panel is to make it easier to edit these files. if you make it too hard, people will just go back to editing the server.properties by hand and that kind of defeats the initial purpose.

**Comment by Antariano** [comment]
Good feedback here. This is mostly due to the fact that we're trying to make things compatible with more than just one version of minecraft (read: different versions, mods, builds and whole other games), which sometimes comes at the cost of having more generic UI elements (at first).

What is happening here is that the `.properties` parser is ignoring certain values that are non-strings or empty (which we fixed in Build 6).

The UI then builds itself out of what the parser returns, which I'll admit isn't perfect. I'll look into ways of making this prettier, but supporting a wide variety of things (even within minecraft, the `.properties` change relatively frequently) comes with it's challenges.

**Comment by Antariano** [comment]
Build 6 improves this. Closing for now
