### ISSUE TITLE
SpaceCP setup hangs

### ISSUE THREAD

**Issue by jithatsonei** [SpaceCP/Bugs#79]
Referenced from https://forums.spacecp.net/topic/345/support-for-boxbilling-whmcs/2

When attempted to setup a server on the daemon it would hang with the error warn: ayy-1: Failed to save config file.ENOENT, open 'C:\Users\Alucard\Desktop\space\servers\ayy-1\server.properties', file=server.properties, server=ayy-1, build=91b40b0be3a445b785e4b07c1d98dab06d5a1353_172

After attempting to create a new server it spat out abunch of HTML and then fails when downloading the jar from GDN.
Logs are here: https://ghostbin.com/paste/7n3bh

Windows 10 x64 Attempted Vanilla.

**Comment by FluffyPancakes** [comment]
Same here - Attempted on Ubuntu Server 14.0.3 x64 (Tried Vanilla & Spigot)

warn: sweg: Failed to save config file.ENOENT: no such file or directory, open '/root/servers/sweg/server.properties', file=server.properties, server=sweg, build=91b40b0be3a445b785e4b07c1d98dab06d5a1353_172
warn: sweg: Couldn't find the java executable named 'java'. Are you sure it's installed?
warn: sweg: Start aborted due to error.
- sweg: Failed to find the 'java' executable.

**Comment by jithatsonei** [comment]
@FluffyPancakes You dont have jre installed. Use `apt-get install default-jdk
` to install it and try again

**Comment by FluffyPancakes** [comment]
I know that, didn't mean to add that as the error.

**Comment by FluffyPancakes** [comment]
Thanks anyways.

**Comment by tlaundal** [comment]
Closing this in favour of #98.
